const $=id=>document.getElementById(id);let teachers=[],selected=null,opened=null;const badges={literature:'Aa',history:'186',algebra:'x/y',identities:'a²',urdu:'ا',narrative:'“ ”',science:'N·S',islam:'علم',arts:'◎'};
async function start(){try{teachers=await(await fetch('teachers.json')).json();teachers.forEach((t,i)=>{const b=document.createElement('button');b.className='teacher';b.innerHTML=`<span class="number">${String(i+1).padStart(2,'0')}</span><span><strong>${t.name}</strong><small>${t.subject}</small></span><span class="badge" aria-hidden="true">${badges[t.theme]}</span>`;b.onclick=()=>choose(t);$('list').append(b)});const t=teachers.find(t=>t.id===location.hash.slice(1));if(t)choose(t)}catch(e){$('list').textContent='The letters could not load. Please refresh and try again.'}}
function choose(t){selected=t;$('gate-name').textContent=t.name;$('code').value='';$('error').textContent='';$('gate').showModal();$('code').focus()}
const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function decrypt(t,code){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(code),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:bytes(t.salt),iterations:210000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(t.iv)},key,bytes(t.cipher));return JSON.parse(new TextDecoder().decode(plain))}
$('code-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;button.textContent='Opening…';try{const code=$('code').value.trim().toUpperCase().replace(/\s/g,'');opened=await decrypt(selected,code);$('gate').close();showGift(selected,opened)}catch(e){$('error').textContent='That code does not match. Please check the code beneath your QR.';$('code').focus()}finally{button.disabled=false;button.textContent='Open my gift'}};
function showGift(t,data){document.body.dataset.theme=t.theme;$('home').hidden=true;$('gift').hidden=false;for(const [id,value] of Object.entries({kicker:t.kicker,recipient:t.name,title:t.title,subject:t.subject,address:t.name,dear:`Dear ${t.name},`,memory:data.memory,thanks:data.thanks}))$(id).textContent=value;$('envelope').hidden=false;$('envelope').classList.remove('breaking');$('envelope').setAttribute('aria-expanded','false');$('letter').hidden=true;$('notes').replaceChildren();data.notes.forEach(([title,body])=>{const d=document.createElement('details');const s=document.createElement('summary');const p=document.createElement('p');s.textContent=title;p.textContent=body;d.append(s,p);if(t.theme==='urdu')d.lang='ur';$('notes').append(d)});$('perspective').hidden=t.theme!=='arts';history.replaceState(null,'',`#${t.id}`);window.scrollTo(0,0)}
$('envelope').onclick=()=>{$('envelope').setAttribute('aria-expanded','true');$('envelope').classList.add('breaking');setTimeout(()=>{$('envelope').hidden=true;$('letter').hidden=false;$('letter').setAttribute('tabindex','-1');$('letter').focus({preventScroll:true})},matchMedia('(prefers-reduced-motion: reduce)').matches?0:550)};
function home(){opened=null;selected=null;delete document.body.dataset.theme;$('gift').hidden=true;$('home').hidden=false;$('memory').textContent='';$('thanks').textContent='';$('notes').replaceChildren();history.replaceState(null,'',location.pathname);window.scrollTo(0,0)}$('back').onclick=home;$('brand').onclick=e=>{e.preventDefault();home()};$('close').onclick=()=>$('gate').close();$('gate').onclick=e=>{if(e.target===$('gate')){const r=$('gate').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('gate').close()}};start();
